# permissions to do viewer beers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beer-viewer-role
rules:
- apiGroups:
  - webapp.beer.lova
  resources:
  - beers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.beer.lova
  resources:
  - beers/status
  verbs:
  - get
